name: Deploy to GitHub Pages

on:
  # main 브랜치에 push할 때 실행
  push:
    branches: [main]

  # 수동으로도 실행 가능
  workflow_dispatch:

# GitHub Pages에 배포하기 위한 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 실행 제한 (한 번에 하나의 배포만)
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 빌드 작업
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: GitHub Pages 설정
        uses: actions/configure-pages@v4

      - name: 아티팩트 업로드
        uses: actions/upload-pages-artifact@v3
        with:
          # 전체 프로젝트 디렉토리 업로드
          path: "."

  # 배포 작업
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: GitHub Pages에 배포
        id: deployment
        uses: actions/deploy-pages@v4
